name: homog
dependencies:
 - python
 - numpy
 - pytest
 - pytest-cov
 - sphinx_rtd_theme
 - ipython
 - pyyaml
 - cryptography
 - pip:
   - hypothesis
   - pytest-sugar
   - pytest-xdist
   - bumpversion
